import {
  columns,
  type SiteRecord,
} from '@/components/functional/Table/columns';
import { DataTable } from '@/components/functional/Table/data-table';

const mockData: SiteRecord[] = [
  {
    name: 'banana.net/',
    hostingLogin: 'banana_admin',
    hostingPassword: 'Banana123!',
    hostingValiduntil: '2025-12-31',
    domainLogin: 'banana_owner',
    domainPassword: 'DomainBanana2025',
    domainValiduntil: '2026-01-15',
    comments: 'Renew hosting before end of year.',
    status: 'active',
    lastModifiedBy: 'Alice',
  },
  {
    name: 'https://cinemaworld.com',
    hostingLogin: 'cinema_admin',
    hostingPassword: 'C1nema!234',
    hostingValiduntil: '2025-09-10',
    domainLogin: 'cinema_owner',
    domainPassword: 'DomCinema#99',
    domainValiduntil: '2026-02-01',
    comments: 'SSL expiring soon.',
    status: 'active',
    lastModifiedBy: 'Bob',
  },
  {
    name: 'https://travelstory.net',
    hostingLogin: 'travel_admin',
    hostingPassword: 'Tr@vel2025',
    hostingValiduntil: '2025-07-01',
    domainLogin: 'travel_owner',
    domainPassword: 'DomTr@vel22',
    domainValiduntil: '2025-12-25',
    comments: 'Consider migrating to VPS.',
    status: 'inactive',
    lastModifiedBy: 'Charlie',
  },
  {
    name: 'techhub.io',
    hostingLogin: 'techhub_root',
    hostingPassword: 'Tech#Hub456',
    hostingValiduntil: '2026-01-20',
    domainLogin: 'techhub_admin',
    domainPassword: 'D0mainTech!',
    domainValiduntil: '2026-03-15',
    comments: 'All systems stable.',
    status: 'active',
    lastModifiedBy: 'Dana',
  },
  {
    name: 'http://foodiesparadise.com',
    hostingLogin: 'foodies_admin',
    hostingPassword: 'F00d!2025',
    hostingValiduntil: '2025-10-05',
    domainLogin: 'foodies_user',
    domainPassword: 'DomFood#11',
    domainValiduntil: '2026-04-22',
    comments: 'Add staging server.',
    status: 'active',
    lastModifiedBy: 'Ethan',
  },
  {
    name: 'https://bookhaven.org/',
    hostingLogin: 'book_admin',
    hostingPassword: 'B00k$Pass',
    hostingValiduntil: '2025-08-12',
    domainLogin: 'book_domain',
    domainPassword: 'D0mBook#44',
    domainValiduntil: '2026-06-30',
    comments: 'High traffic in summer.',
    status: 'active',
    lastModifiedBy: 'Alice',
  },
  {
    name: 'https://fitnesspro.net',
    hostingLogin: 'fit_admin',
    hostingPassword: 'Fit!Pass123',
    hostingValiduntil: '2025-11-01',
    domainLogin: 'fit_domain',
    domainPassword: 'DomFit#2025',
    domainValiduntil: '2026-02-28',
    comments: 'Database upgrade pending.',
    status: 'inactive',
    lastModifiedBy: 'Bob',
  },
  {
    name: 'https://musichub.com',
    hostingLogin: 'music_admin',
    hostingPassword: 'Mus1c@123',
    hostingValiduntil: '2026-01-01',
    domainLogin: 'music_domain',
    domainPassword: 'DomMusiC#1',
    domainValiduntil: '2026-05-05',
    comments: 'Backup scheduled weekly.',
    status: 'active',
    lastModifiedBy: 'Charlie',
  },
  {
    name: 'http://artgallery.net/',
    hostingLogin: 'art_admin',
    hostingPassword: 'Art!Gal22',
    hostingValiduntil: '2025-09-15',
    domainLogin: 'art_domain',
    domainPassword: 'DomArt#77',
    domainValiduntil: '2026-01-30',
    comments: 'Check image hosting costs.',
    status: 'inactive',
    lastModifiedBy: 'Dana',
  },
  {
    name: 'https://greenenergy.org/',
    hostingLogin: 'green_admin',
    hostingPassword: 'Gr33n!Energy',
    hostingValiduntil: '2026-02-10',
    domainLogin: 'green_domain',
    domainPassword: 'DomGreen#55',
    domainValiduntil: '2026-07-20',
    comments: 'Promote eco campaign.',
    status: 'active',
    lastModifiedBy: 'Ethan',
  },
];

const HomePage = () => {
  return (
    <div className='container mx-auto py-10'>
      <DataTable columns={columns} data={mockData} />
    </div>
  );
};

export default HomePage;
